# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(default='user1.jpg', upload_to='upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='passage',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='我的第一个故事', max_length=50),
        ),
    ]
