# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171107_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='passage',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_sex',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_motto',
        ),
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
